### ISSUE TITLE
Problem with event start or end out of range of current view

### ISSUE THREAD

**Issue by RobinMillian** [hbatalhaStch/react-big-scheduler#9]
When an event has a start or end attribute that falls outside the range of the current view, such as a custom view that starts on January 1, 2023 and ends on December 31, 2023, and the event itself starts on November 1, 2022 and ends on February 1, 2023, the end date of the event may be displayed as April 1, 2023. This could be because the month between the start of the event and the start of the view is being applied to the end date of the event.

**Comment by hbatalhaStch** [comment]
Thank you for reporting this, it's really appreciated.

I fixed the issue and released a patch, could you check?

**Comment by RobinMillian** [comment]
Everything looks broken now 
![image](https://user-images.githubusercontent.com/20228329/229731154-4a940b0a-0328-43ab-bde3-5b06bb664f28.png)
Before in 1.1.1 it was looking like 
![image](https://user-images.githubusercontent.com/20228329/229734718-70d34fef-683e-4f6c-9fbb-093782eea20f.png)

**Comment by guillemguerrero** [comment]
Hey, Thanks for your work! Has this issue been solved? It still happens to me, whenever I have an event that has its starting date before the initial view of the chart.

**Comment by hbatalhaStch** [comment]
@guillemguerrero yes I believe it's been solved, however, if it still happening to you could you share more details such as the version you're using and some code?

**Comment by guillemguerrero** [comment]
@hbatalhaStch To be honest, there's a possibility I'm doing something wrong. However, even by just using the example code you mentioned in https://github.com/StephenChou1017/react-big-scheduler/issues/260#issuecomment-1485460853 it already happened. Right now I'm not using this exact same code but I'm still basing my component on it. I'm still working on it.

**Comment by hbatalhaStch** [comment]
Also keep in mind that I didn't thoroughly tested the code in https://github.com/StephenChou1017/react-big-scheduler/issues/260#issuecomment-1485460853 as I use a class component instead of function when I am using the scheduler

**Comment by hbatalhaStch** [comment]
> @hbatalhaStch Yup, it was totally my fault... Sorry for bothering!

That's ok
